-- YengU Supabase/Postgres schema
-- Run in Supabase SQL editor.

create extension if not exists "pgcrypto";

create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'member',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_user_profiles_updated_at on public.user_profiles;
create trigger trg_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.price_alert_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null,
  product_id text,
  source_page text,
  signup_type text not null default 'newsletter',
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_price_alert_subscriptions_email
on public.price_alert_subscriptions (email);

create table if not exists public.affiliate_click_events (
  id bigint generated by default as identity primary key,
  platform text not null,
  product_id text not null,
  page_path text,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists idx_affiliate_click_events_created_at
on public.affiliate_click_events (created_at desc);

create table if not exists public.saved_products (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id text not null,
  notes text,
  created_at timestamptz not null default now(),
  unique (user_id, product_id)
);

alter table public.user_profiles enable row level security;
alter table public.price_alert_subscriptions enable row level security;
alter table public.affiliate_click_events enable row level security;
alter table public.saved_products enable row level security;

-- Profiles: each user reads and updates own profile.
drop policy if exists "profiles_select_own" on public.user_profiles;
create policy "profiles_select_own"
on public.user_profiles
for select
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.user_profiles;
create policy "profiles_update_own"
on public.user_profiles
for update
using (auth.uid() = id);

drop policy if exists "profiles_insert_own" on public.user_profiles;
create policy "profiles_insert_own"
on public.user_profiles
for insert
with check (auth.uid() = id);

-- Price alerts: allow anonymous and authenticated inserts.
drop policy if exists "alerts_insert_any" on public.price_alert_subscriptions;
create policy "alerts_insert_any"
on public.price_alert_subscriptions
for insert
to anon, authenticated
with check (true);

-- Restrict reads to service role by default. Authenticated users can read their own rows.
drop policy if exists "alerts_select_own" on public.price_alert_subscriptions;
create policy "alerts_select_own"
on public.price_alert_subscriptions
for select
to authenticated
using (auth.uid() = user_id);

-- Affiliate click telemetry: allow insert from client.
drop policy if exists "clicks_insert_any" on public.affiliate_click_events;
create policy "clicks_insert_any"
on public.affiliate_click_events
for insert
to anon, authenticated
with check (true);

-- Saved products: owner only.
drop policy if exists "saved_products_select_own" on public.saved_products;
create policy "saved_products_select_own"
on public.saved_products
for select
using (auth.uid() = user_id);

drop policy if exists "saved_products_insert_own" on public.saved_products;
create policy "saved_products_insert_own"
on public.saved_products
for insert
with check (auth.uid() = user_id);

drop policy if exists "saved_products_delete_own" on public.saved_products;
create policy "saved_products_delete_own"
on public.saved_products
for delete
using (auth.uid() = user_id);
